version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: microservices_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  payments_db:
    image: postgres:15-alpine
    container_name: microservices_payments_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    ports:
      - "5434:5432"
    volumes:
      - payments_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: microservices_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  payments_data:
